// Code generated by MockGen. DO NOT EDIT.
// Source: internal/client.go
//
// Generated by this command:
//
//	mockgen -source=internal/client.go -destination tests/mocks/client.go
//

// Package mock_internal is a generated GoMock package.
package mock_internal
