// Code generated by MockGen. DO NOT EDIT.
// Source: internal/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/interface.go -destination tests/mocks/interface.go
//

// Package mock_internal is a generated GoMock package.
package mock_internal

import (
	context "context"
	reflect "reflect"
	time "time"

	internal "github.com/TropicalDog17/tele-bot/internal"
	types "github.com/TropicalDog17/tele-bot/internal/types"
	redis "github.com/redis/go-redis/v9"
	gomock "go.uber.org/mock/gomock"
	telebot "gopkg.in/telebot.v3"
)

// MockCoinGecko is a mock of CoinGecko interface.
type MockCoinGecko struct {
	ctrl     *gomock.Controller
	recorder *MockCoinGeckoMockRecorder
}

// MockCoinGeckoMockRecorder is the mock recorder for MockCoinGecko.
type MockCoinGeckoMockRecorder struct {
	mock *MockCoinGecko
}

// NewMockCoinGecko creates a new mock instance.
func NewMockCoinGecko(ctrl *gomock.Controller) *MockCoinGecko {
	mock := &MockCoinGecko{ctrl: ctrl}
	mock.recorder = &MockCoinGeckoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoinGecko) EXPECT() *MockCoinGeckoMockRecorder {
	return m.recorder
}

// FetchUsdPriceMap mocks base method.
func (m *MockCoinGecko) FetchUsdPriceMap(denoms ...string) (map[string]float64, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range denoms {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FetchUsdPriceMap", varargs...)
	ret0, _ := ret[0].(map[string]float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchUsdPriceMap indicates an expected call of FetchUsdPriceMap.
func (mr *MockCoinGeckoMockRecorder) FetchUsdPriceMap(denoms ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchUsdPriceMap", reflect.TypeOf((*MockCoinGecko)(nil).FetchUsdPriceMap), denoms...)
}

// GetAPIKey mocks base method.
func (m *MockCoinGecko) GetAPIKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAPIKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAPIKey indicates an expected call of GetAPIKey.
func (mr *MockCoinGeckoMockRecorder) GetAPIKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAPIKey", reflect.TypeOf((*MockCoinGecko)(nil).GetAPIKey))
}

// GetPriceInUsd mocks base method.
func (m *MockCoinGecko) GetPriceInUsd(denoms ...string) (map[string]map[string]float64, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range denoms {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPriceInUsd", varargs...)
	ret0, _ := ret[0].(map[string]map[string]float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPriceInUsd indicates an expected call of GetPriceInUsd.
func (mr *MockCoinGeckoMockRecorder) GetPriceInUsd(denoms ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriceInUsd", reflect.TypeOf((*MockCoinGecko)(nil).GetPriceInUsd), denoms...)
}

// MockBot is a mock of Bot interface.
type MockBot struct {
	ctrl     *gomock.Controller
	recorder *MockBotMockRecorder
}

// MockBotMockRecorder is the mock recorder for MockBot.
type MockBotMockRecorder struct {
	mock *MockBot
}

// NewMockBot creates a new mock instance.
func NewMockBot(ctrl *gomock.Controller) *MockBot {
	mock := &MockBot{ctrl: ctrl}
	mock.recorder = &MockBotMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBot) EXPECT() *MockBotMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockBot) Delete(msg telebot.Editable) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBotMockRecorder) Delete(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBot)(nil).Delete), msg)
}

// Handle mocks base method.
func (m_2 *MockBot) Handle(endpoint any, h telebot.HandlerFunc, m ...telebot.MiddlewareFunc) {
	m_2.ctrl.T.Helper()
	varargs := []any{endpoint, h}
	for _, a := range m {
		varargs = append(varargs, a)
	}
	m_2.ctrl.Call(m_2, "Handle", varargs...)
}

// Handle indicates an expected call of Handle.
func (mr *MockBotMockRecorder) Handle(endpoint, h any, m ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{endpoint, h}, m...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockBot)(nil).Handle), varargs...)
}

// ProcessUpdate mocks base method.
func (m *MockBot) ProcessUpdate(u telebot.Update) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ProcessUpdate", u)
}

// ProcessUpdate indicates an expected call of ProcessUpdate.
func (mr *MockBotMockRecorder) ProcessUpdate(u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessUpdate", reflect.TypeOf((*MockBot)(nil).ProcessUpdate), u)
}

// Send mocks base method.
func (m *MockBot) Send(to telebot.Recipient, what any, opts ...any) (*telebot.Message, error) {
	m.ctrl.T.Helper()
	varargs := []any{to, what}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Send", varargs...)
	ret0, _ := ret[0].(*telebot.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockBotMockRecorder) Send(to, what any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{to, what}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockBot)(nil).Send), varargs...)
}

// MockBotClient is a mock of BotClient interface.
type MockBotClient struct {
	ctrl     *gomock.Controller
	recorder *MockBotClientMockRecorder
}

// MockBotClientMockRecorder is the mock recorder for MockBotClient.
type MockBotClientMockRecorder struct {
	mock *MockBotClient
}

// NewMockBotClient creates a new mock instance.
func NewMockBotClient(ctrl *gomock.Controller) *MockBotClient {
	mock := &MockBotClient{ctrl: ctrl}
	mock.recorder = &MockBotClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBotClient) EXPECT() *MockBotClientMockRecorder {
	return m.recorder
}

// CancelOrder mocks base method.
func (m *MockBotClient) CancelOrder(marketID, orderHash string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelOrder", marketID, orderHash)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelOrder indicates an expected call of CancelOrder.
func (mr *MockBotClientMockRecorder) CancelOrder(marketID, orderHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelOrder", reflect.TypeOf((*MockBotClient)(nil).CancelOrder), marketID, orderHash)
}

// GetActiveOrders mocks base method.
func (m *MockBotClient) GetActiveOrders(marketId string) ([]types.LimitOrderInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveOrders", marketId)
	ret0, _ := ret[0].([]types.LimitOrderInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveOrders indicates an expected call of GetActiveOrders.
func (mr *MockBotClientMockRecorder) GetActiveOrders(marketId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveOrders", reflect.TypeOf((*MockBotClient)(nil).GetActiveOrders), marketId)
}

// GetAddress mocks base method.
func (m *MockBotClient) GetAddress() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAddress")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAddress indicates an expected call of GetAddress.
func (mr *MockBotClientMockRecorder) GetAddress() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAddress", reflect.TypeOf((*MockBotClient)(nil).GetAddress))
}

// GetBalances mocks base method.
func (m *MockBotClient) GetBalances(address string, denoms []string) (map[string]float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalances", address, denoms)
	ret0, _ := ret[0].(map[string]float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalances indicates an expected call of GetBalances.
func (mr *MockBotClientMockRecorder) GetBalances(address, denoms any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalances", reflect.TypeOf((*MockBotClient)(nil).GetBalances), address, denoms)
}

// GetDecimal mocks base method.
func (m *MockBotClient) GetDecimal(denom string) int32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDecimal", denom)
	ret0, _ := ret[0].(int32)
	return ret0
}

// GetDecimal indicates an expected call of GetDecimal.
func (mr *MockBotClientMockRecorder) GetDecimal(denom any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDecimal", reflect.TypeOf((*MockBotClient)(nil).GetDecimal), denom)
}

// GetPrice mocks base method.
func (m *MockBotClient) GetPrice(ticker string) (float64, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrice", ticker)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetPrice indicates an expected call of GetPrice.
func (mr *MockBotClientMockRecorder) GetPrice(ticker any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrice", reflect.TypeOf((*MockBotClient)(nil).GetPrice), ticker)
}

// GetRedisInstance mocks base method.
func (m *MockBotClient) GetRedisInstance() internal.RedisClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRedisInstance")
	ret0, _ := ret[0].(internal.RedisClient)
	return ret0
}

// GetRedisInstance indicates an expected call of GetRedisInstance.
func (mr *MockBotClientMockRecorder) GetRedisInstance() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRedisInstance", reflect.TypeOf((*MockBotClient)(nil).GetRedisInstance))
}

// PlaceSpotOrder mocks base method.
func (m *MockBotClient) PlaceSpotOrder(denomIn, denomOut string, amount, price float64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlaceSpotOrder", denomIn, denomOut, amount, price)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PlaceSpotOrder indicates an expected call of PlaceSpotOrder.
func (mr *MockBotClientMockRecorder) PlaceSpotOrder(denomIn, denomOut, amount, price any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlaceSpotOrder", reflect.TypeOf((*MockBotClient)(nil).PlaceSpotOrder), denomIn, denomOut, amount, price)
}

// SetPrice mocks base method.
func (m *MockBotClient) SetPrice(ticker string, price float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPrice", ticker, price)
}

// SetPrice indicates an expected call of SetPrice.
func (mr *MockBotClientMockRecorder) SetPrice(ticker, price any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPrice", reflect.TypeOf((*MockBotClient)(nil).SetPrice), ticker, price)
}

// ToMessage mocks base method.
func (m *MockBotClient) ToMessage(order types.LimitOrderInfo, showDetail bool) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToMessage", order, showDetail)
	ret0, _ := ret[0].(string)
	return ret0
}

// ToMessage indicates an expected call of ToMessage.
func (mr *MockBotClientMockRecorder) ToMessage(order, showDetail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToMessage", reflect.TypeOf((*MockBotClient)(nil).ToMessage), order, showDetail)
}

// TransferToken mocks base method.
func (m *MockBotClient) TransferToken(to string, amount float64, denom string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferToken", to, amount, denom)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransferToken indicates an expected call of TransferToken.
func (mr *MockBotClientMockRecorder) TransferToken(to, amount, denom any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferToken", reflect.TypeOf((*MockBotClient)(nil).TransferToken), to, amount, denom)
}

// MockRedisClient is a mock of RedisClient interface.
type MockRedisClient struct {
	ctrl     *gomock.Controller
	recorder *MockRedisClientMockRecorder
}

// MockRedisClientMockRecorder is the mock recorder for MockRedisClient.
type MockRedisClientMockRecorder struct {
	mock *MockRedisClient
}

// NewMockRedisClient creates a new mock instance.
func NewMockRedisClient(ctrl *gomock.Controller) *MockRedisClient {
	mock := &MockRedisClient{ctrl: ctrl}
	mock.recorder = &MockRedisClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisClient) EXPECT() *MockRedisClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRedisClient) Get(ctx context.Context, key string) *redis.StringCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(*redis.StringCmd)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockRedisClientMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRedisClient)(nil).Get), ctx, key)
}

// HSet mocks base method.
func (m *MockRedisClient) HSet(ctx context.Context, key string, values ...any) *redis.IntCmd {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range values {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HSet", varargs...)
	ret0, _ := ret[0].(*redis.IntCmd)
	return ret0
}

// HSet indicates an expected call of HSet.
func (mr *MockRedisClientMockRecorder) HSet(ctx, key any, values ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, values...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HSet", reflect.TypeOf((*MockRedisClient)(nil).HSet), varargs...)
}

// Set mocks base method.
func (m *MockRedisClient) Set(arg0 context.Context, arg1 string, arg2 any, arg3 time.Duration) *redis.StatusCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*redis.StatusCmd)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockRedisClientMockRecorder) Set(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockRedisClient)(nil).Set), arg0, arg1, arg2, arg3)
}
