ActiveOrders = "💸 Active Orders"
AlertMessage = "*🚨 Alert ID:* {{.AlertID}}\n*📈 {{.Name}} {{.Symbol}}/USDT*\n⏰ Alert me when price is *{{.Condition}} ${{.Value}}*\n💰 Current price in USD: ${{.CurrentPrice}}"
AlertMessagePercentage = "*🚨 Alert ID:* {{.AlertID}}\n*📈 {{.Name}} {{.Symbol}}/USDT*\n⏰ Alert me when price is *{{.Condition}} {{.Value}}% last 24h*\n💰 Current price in USD: ${{.CurrentPrice}}"
Amount = "📈 Amount"
AmountSection = "💰 Amount: "
Back = "Back"
BiggestGainer24h = "🚀 Biggest Gainer 24h"
BiggestLoser24h = "📉 Biggest Loser 24h"
BiggestVolume24h = "📊 Biggest Volume 24h"
BuyLimitOrder = "📈 Buy"
CancelOrder = "Cancel Order"
ChangeDefaultLimitPair = "🪙 Change Default Limit Pair"
ChangeLanguage = "🌐 Change Language"
ChangePassword = "🔑 Change Password"
ClientNotFound = "Client not found"
Close = "Close"
ConfirmLimitOrder = "Confirm"
ConfirmOrder = "✅ Confirm Order"
CreateAlertMessage = "Please input the alert in the format \n *<<symbol>> <<condition>> <<value>>*\n*For example*: BTC up 1000$\nETH down 10%\nATOM over 1000$\nBTC under 50000$\n"
CreatePriceAlert = "🔔 Create Price Alert"
CustomAmount = "Custom amount"
CustomToken = "Custom token"
DeletePriceAlert = "🔔 Delete Price Alert"
DisablePassword = "🔒 Disable Password"
EnterCancelOrderId = "Enter the order ID to cancel"
EnterCustomAmount = "Please enter the custom amount:"
EnterCustomToken = "Please enter the custom token:"
EnterRecipientAddress = "Please enter the recipient address:"
ErrorSendingToken = "Error sending token"
FiftyDollar = "💰 $5"
FillAllFields = "Please fill in all required fields, missing {{.Field}}"
FiveHundredDollar = "💶 $50"
HundredDollar = "💸 $10"
InlineAtom = "ATOM"
InlineInj = "INJ"
InvalidAmount = "Invalid amount"
LimitOrder = "🚀 Limit Order"
LimitOrderText = "📊 Limit Orders\n\nBuy or Sell tokens automatically at your desired price.\n1. Choose to Buy or Sell.\n2. Choose the Token to Buy or Sell.\n3. Select the amount to Buy or Sell.\n4. Set your target buy or sell price.\n5. Click Create Order and Review, Confirm.\n\nTo manage or view unfilled orders, click Active Orders."
Menu = "Menu"
MissingField = "missing field"
NoActiveOrders = "No active orders"
PayWith = "💳 Pay With"
Price = "💰 Price"
PriceAlert = "🔔 Price Alert"
RecipientAddress = "recipient address"
RecipientNotSet = "Recipient not set"
RecipientSection = "👤 Recipient: "
RecipientSet = "Recipient set"
SelectTokenToSend = "Select the token to send:"
SelectedAmount = "Selected amount"
SelectedToken = "Selected token"
SellLimitOrder = "📉 Sell"
Send = "Send"
SendToken = "💸 Send Token"
Settings = "⚙ Settings"
ShowAccount = "👤 Show Account"
SpotOrder = "📊 Spot Order"
TenDollar = "💵 $1"
Token = "🪙 Token"
TokenSection = "🪙 Token: "
TokenSent = "Sent {{.Amount}} {{.Token}} to {{.Address}}, with tx hash {{.TxHash}}"
Transfer = "Transfer"
TwoHundredDollar = "🪙 $20"
UpdatePriceAlert = "🔔 Update Price Alert"
ViewBalances = "ℹ View Balances"
ViewMarket = "📈 View Market"
ViewPriceAlert = "🔔 View Price Alert"
biggest_gainers_24h = "Here are the biggest gainers in the last 24h 📈📈📈 \n "
biggest_losers_24h = "Here are the biggest losers in the last 24h 📉📉📉 \n "
biggest_volume_24h = "Here are the biggest volume in the last 24h 📊📊📊 \n "
display_data_string = "{{.Ticker}}\n\nChange: {{.Change}}% {{.Icon}}\n\nPrice: ${{.Price}} 📊 Volume: ${{.Volume}}"
error_fetching_data = "Error fetching data: {{.ErrorMessage}}"
market_quick_look = "Here you can have a quick look at the market the last 24h"
passwordAccepted = "Password accepted. You can perform your action again"
sessionExpired = "Session expired! Please enter your password"
